/**
 * Oyun durumunu yöneten merkezi sınıf
 */

const GameState = (function () {
    // Varsayılan sevgi mesajları (Tüm mektuplar DEFAULT_LOVE_MESSAGES olarak dışa aktarılıyor)
    const DEFAULT_LOVE_MESSAGES = [
        "Havin'im, gözlerindeki yıldızlar kalbimin uçsuz bucaksız evreninde parıldıyor.",
        "Havin'im, seninle her anım hayatımın en değerli hazinesi.",
        "Havin'im, sana olan sevgim zamanın ötesinde sonsuza dek yaşayacak.",
        "Havin'im, her sabah gözlerimi açtığımda ilk düşüncem sen oluyorsun.",
        "Havin'im, kalbim senin sevginle dolu olduğu için bu kadar güçlü atıyor.",
        "Havin'im, adın dudaklarımdan dökülen en tatlı melodi.",
        "Havin'im, senin gülüşün hayatımın en güzel manzarası.",
        "Havin'im, seninle geçirdiğim her an kalbimde sonsuz bir iz bırakıyor.",
        "Havin'im, düşüncelerim seninle dolu, kalbim senin sevginle nefes alıyor.",
        "Havin'im, seni sevmek hayatımın en büyük serüveni ve en güzel armağanı.",
        "Havin'im, her gün seni daha çok seviyorum, sanki bu mümkünmüş gibi.",
        "Havin'im, senin varlığın hayatıma anlam ve güzellik katıyor.",
        "Havin'im, seninle geçen her gün hayatımın en değerli hediyesi.",
        "Havin'im, senin aşkın benim için yaşam kaynağı.",
        "Havin'im, kısa bir an için bile olsa seni düşünmediğim bir gün yok.",
        "Havin'im, kalbim sonsuza dek senin için atacak.",
        "Havin'im, seninle paylaştığım her gülüş hayatımın hazinesi.",
        "Havin'im, sana olan aşkım her gün daha da derinleşiyor.",
        "Havin'im, sen benim rüyalarımın gerçekleşmiş halisin.",
        "Havin'im, sevgin beni her gün yeniden canlandırıyor.",
        "Havin'im, sensiz geçen her an eksik bir an.",
        "Havin'im, dünyanın tüm güzellikleri senin gülüşünde gizli.",
        "Havin'im, hayatımın anlamı sensin.",
        "Havin'im, seninle nefes alıyorum, seninle yaşıyorum.",
        "Havin'im, güneş sisteminin merkezi sensin, etrafında dönüyorum.",
        "Havin'im, seni düşündüğümde kalbim bir çocuk gibi heyecanlanıyor.",
        "Havin'im, her gün seninle uyanmak hayatımın en büyük dileği.",
        "Havin'im, sen benim en güzel şiirim, en derin şarkım, en anlamlı hikayemsin.",
        "Havin'im, gözlerinde kaybolmak hayatımın en büyük zevki.",
        "Havin'im, senin gülüşün benim için en büyük mutluluk kaynağı.",
        "Havin'im, sen olmasaydın hayatım bu kadar anlamlı ve güzel olmazdı.",
        "Havin'im, yıldızları sayabilirsin ama sana olan sevgimi asla ölçemezsin.",
        "Havin'im, kalbimde açan en güzel çiçeksin.",
        "Havin'im, sen benim en değerli hazinemsin, seni sonsuza dek saklamak istiyorum.",
        "Havin'im, senin aşkın beni her gün yeniden canlandırıyor.",
        "Havin'im, seninle yaşadığım her an, hayatımın film şeridi gibi tekrar tekrar izlemek istediğim anılar.",
        "Havin'im, sen benim kalbimin en derinlerinde sakladığım en değerli mücevherimsin.",
        "Havin'im, her gün seninle yeni anılar biriktirmek istiyorum.",
        "Havin'im, sensiz bir hayat düşünemiyorum, sen benim her şeyimsin.",
        "Havin'im, sen benim sonsuz aşkım, tek gerçeğimsin.",
        "Havin'im, seninle geçirdiğim her an hayatımın en değerli parçası.",
        "Havin'im, seni her gün daha çok sevmek için doğmuşum.",
        "Havin'im, sen benim kalbimde sonsuza dek yaşayacak olan aşkımsın.",
        "Havin'im, seni sevmek nefes almak kadar doğal ve vazgeçilmez.",
        "Havin'im, senin için yazdığım her kelime kalbimin sesi.",
        "Havin'im, hayatımda olduğun için her gün şükrediyorum.",
        "Havin'im, senin sevgin benim için en güzel armağan.",
        "Havin'im, seninle geçen her saniye kalbimde sonsuz bir mutluluk bırakıyor.",
        "Havin'im, sen benim hayatımın anlamı, kalbimin atma sebebisin.",
        "Havin'im, seni sevdiğim kadar sevilmeyi hak ediyorsun.",
        "Havin'im, sana duyduğum sevgi her geçen gün katlanarak büyüyor.",
        "Havin'im, seninle olmak hayallerimin ötesinde bir mutluluk.",
        "Havin'im, sen benim en büyük şansım, en değerli varlığımsın.",
        "Havin'im, sana olan sevgim sonsuza kadar sürecek.",
        "Havin'im, senin sevgin benim için bir hazine, onu kalbimde saklıyorum.",
        "Havin'im, seninle her an büyülü bir masal gibi.",
        "Havin'im, sen benim kalbimde taht kurmuş kraliçemsin.",
        "Havin'im, seni tanıdığım gün hayatımın en şanslı günüydü.",
        "Havin'im, seninle her şey çok daha güzel ve anlamlı.",
        "Havin'im, sana duyduğum sevgi her gün daha da büyüyor.",
        "Havin'im, sen benim kalbimin sahibi, ruhumun eşisin.",
        "Havin'im, seni sevmek yaşamımın en güzel deneyimi.",
        "Havin'im, sen benim hayatımın en büyük hediyesisin.",
        "Havin'im, sensiz geçen her an eksik ve anlamsız.",
        "Havin'im, seninle her şey mümkün, her şey çok daha güzel.",
        "Havin'im, senin varlığın hayatımı aydınlatıyor.",
        "Havin'im, seni sevmek yaşamımın amacı haline geldi.",
        "Havin'im, sen benim sonsuz ilham kaynağımsın.",
        "Havin'im, seninle geçirdiğim her an paha biçilemez.",
        "Havin'im, sen benim kalbimin en derinlerinde sakladığım hazinesin.",
        "Havin'im, sana olan sevgim her gün biraz daha artıyor.",
        "Havin'im, senin sevgin benim için bir yaşam kaynağı.",
        "Havin'im, seni her gün yeniden keşfetmek istiyorum.",
        "Havin'im, sen benim en büyük tutkum, en derin sevdamsın.",
        "Havin'im, sana olan aşkım sonsuzluğa uzanan bir yolculuk.",
        "Havin'im, seninle yaşadığım her an hayatımın en değerli anısı.",
        "Havin'im, sen benim dünyamın merkezi, kalbimin atma sebebisin.",
        "Havin'im, seni seviyorum, hem de kelimelerle anlatılamayacak kadar çok.",
        "Havin'im, senin sevgin benim için en büyük motivasyon kaynağı.",
        "Havin'im, seninle hayat çok daha anlamlı ve güzel.",
        "Havin'im, sen benim hayallerimin ötesinde bir gerçeksin.",
        "Havin'im, sana olan sevgim her geçen gün daha da derinleşiyor.",
        "Havin'im, senin sevgin benim için en değerli hazine.",
        "Havin'im, seninle her an bir mutluluk hikâyesi yazıyoruz.",
        "Havin'im, sen benim kalbimin en özel köşesinde sakladığım sevdamsın.",
        "Havin'im, seni sevmek hayatımın en güzel serüveni.",
        "Havin'im, sen benim hayatımın en büyük şansı, en güzel armağanısın.",
        "Havin'im, sana olan sevgim her gün biraz daha büyüyor.",
        "Havin'im, senin sevgin benim için yaşam enerjisi.",
        "Havin'im, seninle geçirdiğim her dakika benim için paha biçilemez.",
        "Havin'im, sen benim kalbimin tek sahibi, ruhumun eşisin.",
        "Havin'im, seni her gün yeniden sevmek istiyorum.",
        "Havin'im, sen benim hayallerimin ötesinde bir gerçeksin.",
        "Havin'im, sana olan sevgim sonsuza dek sürecek.",
        "Havin'im, senin varlığın hayatımı aydınlatıyor.",
        "Havin'im, seni tanıdığım an hayatımın dönüm noktasıydı.",
        "Havin'im, sen benim en derin tutkum, en büyük sevdamsın.",
        "Havin'im, senin sevgin benim için bir yaşam kaynağı.",
        "Havin'im, seninle hayat çok daha anlamlı ve değerli.",
        "Havin'im, sen benim en büyük aşkım, en değerli varlığımsın.",
        "Havin'im, sana olan sevgim her gün biraz daha artıyor.",
        "Havin'im, senin sevgin benim için en büyük mutluluk sebebi.",
        "Havin'im, seninle geçen her an hayatımın en güzel anısı.",
        "Havin'im, sen benim kalbimin tek hakimi, ruhumun eşisin.",
        "Havin'im, seni düşündüğümde yüzümde beliren gülümseme hiç silinmiyor.",
        "Havin'im, senin aşkınla yaşıyorum, senin sevginle nefes alıyorum.",
        "Havin'im, sen benim hayatımın en büyük anlamı, en derin sevdamsın.",
        "Havin'im, sana olan sevgim her geçen gün daha da güçleniyor.",
        "Havin'im, senin sevgin benim için en değerli hazine.",
        "Havin'im, seninle her an bir masal gibi, bir rüya gibi geçiyor.",
        "Havin'im, sen benim kalbimin tek sahibi, ruhumun eşisin.",
        "Havin'im, seni her gün yeniden sevmek istiyorum.",
        "Havin'im, sen benim en büyük şansım, en değerli varlığımsın.",
        "Havin'im, sana olan sevgim sonsuzluğa uzanıyor.",
        "Havin'im, senin sevgin benim için bir yaşam enerjisi.",
        "Havin'im, seninle geçirdiğim her an benim için paha biçilemez.",
        "Havin'im, sen benim kalbimin en özel köşesinde sakladığım sevdamsın.",
        "Havin'im, seni sevmek hayatımın en büyük mutluluğu.",
        "Havin'im, sen benim hayatımın anlamı, varoluş sebebimsin.",
        "Havin'im, sana olan aşkım her gün daha da derinleşiyor.",
        "Havin'im, senin sevgin benim için en büyük güç kaynağı.",
        "Havin'im, seninle hayat çok daha anlamlı ve güzel.",
        "Havin'im, sen benim hayallerimin ötesinde bir gerçeksin.",
        "Havin'im, sana olan sevgim sonsuza dek sürecek.",
        "Havin'im, her günü seninle geçirmek istiyorum, sonsuza dek.",
        "Havin'im, sen benim kalbimin tek hakimi, ruhumun diğer yarısısın.",
        "Havin'im, seni düşündüğümde kalbim hızla atmaya başlıyor.",
        "Havin'im, senin aşkınla dolu bir hayat yaşamak en büyük dileğim.",
        "Havin'im, sen benim en büyük ilham kaynağım, en derin tutkumsun.",
        "Havin'im, sana olan sevgim her geçen gün katlanarak büyüyor.",
        "Havin'im, senin sevgin benim için en değerli armağan.",
        "Havin'im, seninle geçen her an hayatımın en kıymetli zamanı.",
        "Havin'im, sen benim kalbimin tek sahibi, ruhumun eşisin.",
        "Havin'im, seni her sabah yeniden sevmek hayatımın en büyük zevki.",
        "Havin'im, sen benim en büyük şansım, en değerli hazinesin.",
        "Havin'im, sana olan sevgim sonsuzluğa kadar uzanıyor.",
        "Havin'im, senin sevgin benim için bir yaşam enerjisi.",
        "Havin'im, seninle geçirdiğim her an benim için paha biçilemez.",
        "Havin'im, sen benim kalbimin en özel köşesinde sakladığım sevdamsın.",
        "Havin'im, seni tanıdığım gün hayatımın en güzel günüydü.",
        "Havin'im, sen benim hayatımın anlamı, varoluş sebebimsin.",
        "Havin'im, sana olan aşkım her gün daha da derinleşiyor.",
        "Havin'im, senin sevgin benim için en büyük motivasyon.",
        "Havin'im, seninle hayat çok daha renkli ve anlamlı.",
        "Havin'im, sen benim hayallerimin ötesinde bir mucizesin.",
        "Havin'im, sana olan sevgim zamanın sınırlarını aşıyor.",
        "Havin'im, senin varlığın hayatımın en büyük hediyesi.",
        "Havin'im, sen benim kalbimin tek sahibi, ruhumun diğer yarısısın.",
        "Havin'im, seni düşünmek bile beni mutlu etmeye yetiyor.",
        "Havin'im, senin aşkınla dolu bir ömür geçirmek istiyorum.",
        "Havin'im, sen benim en büyük tutkum, en derin sevdamsın.",
        "Havin'im, sana olan sevgim her geçen gün daha da güçleniyor.",
        "Havin'im, senin sevgin benim için en büyük hazine.",
        "Havin'im, seninle geçirdiğim her an bir peri masalı gibi büyülü.",
        "Havin'im, sen benim kalbimin tek hakimi, ruhumun ışığısın.",
        "Havin'im, seni sevmek hayatımın en anlamlı eylemi.",
        "Havin'im, sen benim en büyük şansım, en değerli varlığımsın.",
        "Havin'im, sana olan sevgim zaman ve mekanın ötesinde.",
        "Havin'im, senin sevgin benim için bir yaşam kaynağı.",
        "Havin'im, seninle geçirdiğim her anın değerini biliyorum.",
        "Havin'im, sen benim kalbimin en özel köşesinde sakladığım hazinesin.",
        "Havin'im, seni ilk gördüğüm an hayatımın dönüm noktasıydı.",
        "Havin'im, sen benim hayatımın anlamı, kalbimin sesi, gücümün kaynağısın.",
        "Havin'im, sana olan sevgim her geçen gün daha da derinleşiyor.",
        "Havin'im, senin aşkın beni her gün yeniden hayata bağlıyor.",
        "Havin'im, seninle hayat çok daha güzel ve anlamlı.",
        "Havin'im, sen benim hayallerimin ötesinde bir hediyesin.",
        "Havin'im, sana olan sevgim sonsuza dek yaşayacak.",
        "Havin'im, senin varlığın hayatımın en büyük zenginliği.",
        "Havin'im, sen benim kalbimin değişmez sahibi, ruhumun eşisin.",
        "Havin'im, seni düşündüğümde dünya duruyor gibi hissediyorum.",
        "Havin'im, senin aşkınla dolu bir hayat yaşamak en büyük mutluluğum.",
        "Havin'im, sen benim en büyük ilhamım, en derin tutkumsun.",
        "Havin'im, sana olan sevgim her geçen gün daha da büyüyor.",
        "Havin'im, senin sevgin benim için yaşam enerjisi.",
        "Havin'im, seninle geçirdiğim her an hayatımın en güzel anısı.",
        "Havin'im, sen benim kalbimin değişmez sahibi, ruhumun eşisin.",
        "Havin'im, seni her an yeniden sevmek istiyorum.",
        "Havin'im, sen benim en büyük şansım, en değerli varlığımsın.",
        "Havin'im, sana olan sevgim zamanın ve mekanın ötesinde.",
        "Havin'im, senin sevgin benim için yaşam kaynağı.",
        "Havin'im, seninle geçirdiğim her an benim için bir hazine.",
        "Havin'im, sen benim kalbimin en derin köşesinde sakladığım sevdamsın.",
        "Havin'im, seni görmek her sabah yeniden doğmak gibi.",
        "Havin'im, sen benim hayatımın anlamı, kalbimdeki tek gerçeksin.",
        "Havin'im, sana olan aşkım her gün derinleşiyor, büyüyor.",
        "Havin'im, senin sevgin benim için en büyük armağan.",
        "Havin'im, seninle hayat çok daha anlamlı, çok daha güzel.",
        "Havin'im, sen benim hayallerimden bile daha güzel bir gerçeksin.",
        "Havin'im, sana olan sevgim sonsuzluğa kadar uzanıyor.",
        
        // 100 Yeni Aşk Mesajı (Her birinde "Havin'im" ifadesi var)
        "Havin'im, gözlerindeki ışıltı güneşten daha parlak.",
        "Havin'im, seninle her gün yeni bir macera.",
        "Havin'im, senin gülüşün dünyadaki en güzel müzik.",
        "Havin'im, her sabah seni düşünerek uyanmak en büyük mutluluğum.",
        "Havin'im, aşkımız zamanla daha da güçleniyor.",
        "Havin'im, her dileğim seninle bir ömür geçirmek.",
        "Havin'im, sensiz bir hayat düşünemiyorum bile.",
        "Havin'im, ellerini tuttuğumda dünya duruyor gibi hissediyorum.",
        "Havin'im, her bakışında kalbim hızlanıyor.",
        "Havin'im, seninle paylaşılan her an özel.",
        "Havin'im, seni sevmek hayattaki en kolay şey.",
        "Havin'im, aşkımız her zorlukta büyüyor ve güçleniyor.",
        "Havin'im, adını her söylediğimde içim huzurla doluyor.",
        "Havin'im, hayallerimizin peşinden birlikte koşmak istiyorum.",
        "Havin'im, varlığın hayatıma anlam katıyor.",
        "Havin'im, sensiz bir günü bile düşünmek istemiyorum.",
        "Havin'im, seni her gün daha fazla seviyorum.",
        "Havin'im, gülüşünde kaybolmak en büyük arzum.",
        "Havin'im, kalbim sadece senin için atıyor.",
        "Havin'im, seninle yaşlanmak istiyorum.",
        "Havin'im, aşkımız gün geçtikçe büyüyor, derinleşiyor.",
        "Havin'im, hayatımın her anında seni hissediyorum.",
        "Havin'im, sen benim en güzel hayalimsin.",
        "Havin'im, her yeni gün seninle daha güzel.",
        "Havin'im, aşkımız zaman geçtikçe daha değerli oluyor.",
        "Havin'im, senin yanındayken kendim olabiliyorum.",
        "Havin'im, senden başka kimseyi düşünemiyorum.",
        "Havin'im, her zorlukta bana güç veriyorsun.",
        "Havin'im, kalbimde sadece senin için yer var.",
        "Havin'im, aşkımız her şeyden daha güçlü.",
        "Havin'im, ömrümün sonuna kadar seni seveceğim.",
        "Havin'im, adın dudaklarımda en güzel kelime.",
        "Havin'im, seninle paylaştığım anılar paha biçilemez.",
        "Havin'im, senin aşkın her şeye değer.",
        "Havin'im, seni düşünmek bile kalbimi ısıtıyor.",
        "Havin'im, her zaman senin yanında olmak istiyorum.",
        "Havin'im, gözlerinin içine baktığımda geleceğimizi görüyorum.",
        "Havin'im, sen benim en büyük şansımsın.",
        "Havin'im, hayatımda olduğun için çok şanslıyım.",
        "Havin'im, seninle geçirdiğim her an bir hazine.",
        "Havin'im, sevgin hayatımın en değerli parçası.",
        "Havin'im, seni sevmekten asla vazgeçmeyeceğim.",
        "Havin'im, birlikte geleceğe adım atmak istiyorum.",
        "Havin'im, sen benim kalbimin sahibisin.",
        "Havin'im, seninle her gün yeni bir başlangıç.",
        "Havin'im, aşkımız her yeni günle birlikte büyüyor.",
        "Havin'im, senin yanında olmak benim için en büyük mutluluk.",
        "Havin'im, hayallerimizi birlikte gerçekleştireceğiz.",
        "Havin'im, aşkımız sonsuzluğa kadar sürecek.",
        "Havin'im, seninle yan yana yürümek istiyorum.",
        "Havin'im, her yeni sabah senin aşkınla uyanıyorum.",
        "Havin'im, seninle olmak her şeyi değerli kılıyor.",
        "Havin'im, varlığın benim için en büyük hediye.",
        "Havin'im, seninle hayat daha anlamlı.",
        "Havin'im, adın kalbimde yazılı.",
        "Havin'im, seninle kurduğumuz hayaller gerçek olacak.",
        "Havin'im, sen benim hayatımın ışığısın.",
        "Havin'im, aşkımız her engeli aşabilir.",
        "Havin'im, birbirimize olan sevgimiz her şeyden güçlü.",
        "Havin'im, seni düşününce yüzümde bir gülümseme beliriyor.",
        "Havin'im, kalbimi sonsuza dek sana emanet ettim.",
        "Havin'im, herkes bizim gibi sevebilseydi, dünya çok daha güzel olurdu.",
        "Havin'im, senin yanında olduğum için çok mutluyum.",
        "Havin'im, sevgin bana yaşama sevinci veriyor.",
        "Havin'im, seninle her anımız çok özel.",
        "Havin'im, varlığın hayatımın en büyük zenginliği.",
        "Havin'im, sana hayatım boyunca sadık kalacağım.",
        "Havin'im, adını söylemek bile beni mutlu ediyor.",
        "Havin'im, birlikte her zorluğu aşabileceğimize inanıyorum.",
        "Havin'im, senin aşkın benim için bir armağan.",
        "Havin'im, seninle gurur duyuyorum.",
        "Havin'im, sevgin bana güç veriyor.",
        "Havin'im, seninle mutluluğun tadını çıkarıyorum.",
        "Havin'im, her anında yanında olmak istiyorum.",
        "Havin'im, seni hak ettiğin gibi seviyorum.",
        "Havin'im, aşkımız tüm zorluklara rağmen güçleniyor.",
        "Havin'im, her günümüzü daha güzel kılıyoruz.",
        "Havin'im, seni düşünmek her zaman içimi ısıtıyor.",
        "Havin'im, sevgi dolu kalbin en büyük hazinemiz.",
        "Havin'im, seninle birlikte olmak en büyük hayalimdi.",
        "Havin'im, kalbimin her atışı senin için.",
        "Havin'im, seninle dünyanın en mutlu insanı oluyorum.",
        "Havin'im, hayatıma anlam kattığın için teşekkür ederim.",
        "Havin'im, sevgin benim rehberim oldu.",
        "Havin'im, seninle her yeni güne umutla uyanıyorum.",
        "Havin'im, sana olan sevgim her gün yenileniyor.",
        "Havin'im, seninle birlikte yaşamak en büyük mutluluğum.",
        "Havin'im, kalbimi ilk çaldığın günden beri senindir.",
        "Havin'im, sen benim ilham kaynağımsın.",
        "Havin'im, sana olan sevgim tarif edilemez.",
        "Havin'im, varlığın hayatımın anlamı.",
        "Havin'im, seninle her günümüz bir başka güzel.",
        "Havin'im, seni düşünmek bile beni mutlu etmeye yetiyor.",
        "Havin'im, aşkımız iki kalbi birleştiren en güçlü bağ.",
        "Havin'im, seninle geçirdiğim her an çok değerli.",
        "Havin'im, adın kalbime kazınmış durumda.",
        "Havin'im, seni sevmek hayatımın en anlamlı kararı.",
        "Havin'im, seninle olduğum her an çok özel.",
        "Havin'im, aşkın beni her gün daha iyi bir insan yapıyor.",
        
        // 500 Yeni Romantik Aşk Mesajı (Her mesajda "Havin'im" ifadesi bulunuyor)
        "Havin'im, gözlerindeki yıldızlar geceme ışık tutuyor, her bakışında kalbim tekrar baştan âşık oluyor.",
        "Havin'im, seninle el ele deniz kenarında yürürken, dünyanın en mutlu insanı olduğumu hissediyorum.",
        "Havin'im, senin için her sabah uyanmaktan daha güzel bir motivasyon olamaz.",
        "Havin'im, dudaklarındaki tebessüm hayattaki en sevdiğim manzara.",
        "Havin'im, ismini her söylediğimde kalbimden geçen elektrik akımını hissedebiliyorum.",
        "Havin'im, seninle geçirdiğim her an, hayatımdaki en değerli koleksiyonum.",
        "Havin'im, kokun hafızamda öyle derin yer etmiş ki, gözlerimi kapattığımda yanımda olduğunu hissediyorum.",
        "Havin'im, seninle kadehlerimizi tokuşturarak paylaştığımız her şarap, hayatımın en tatlı anılarından.",
        "Havin'im, gülüşünün sesini duymak için sabahları daha erken uyanmaya değer.",
        "Havin'im, seninle birlikte yaşlanmak ve her anı paylaşmak en büyük hayalim.",
        "Havin'im, ellerinin sıcaklığı kış günlerinde ihtiyacım olan tek şey.",
        "Havin'im, seni gördüğüm ilk an, zamanın durduğu ve hayatımın değiştiği andı.",
        "Havin'im, seninle dans etmek yıldızlarla vals yapmak gibi büyülü.",
        "Havin'im, senin yanında olmak, dünyanın en huzurlu limanında demir atmak gibi.",
        "Havin'im, saçlarının kokusunda kaybolmak için her şeyimi verirdim.",
        "Havin'im, en sevdiğim şarkıların hepsinde senin adını duyuyorum.",
        "Havin'im, sana yazdığım her mektupta kalbimin bir parçasını bırakıyorum.",
        "Havin'im, seninle birlikte uyandığım her sabah, hayatımın en özel hediyesi.",
        "Havin'im, seninle paylaştığım kahvenin tadı, dünyadaki en lezzetli şey.",
        "Havin'im, gözlerinde kaybolduğumda, cennette olduğumu hissediyorum.",
        "Havin'im, seninle birlikte yağmurda ıslanmak, hayatımın en romantik anısı.",
        "Havin'im, elini tuttuğumda dünya durdu, kalbim seninle sonsuza kadar koşmaya başladı.",
        "Havin'im, seninle geçirdiğim her an, hayatım boyunca yaşamak istediğim bir masal.",
        "Havin'im, senin gülüşün karanlık gecelerimde parlayan yıldız.",
        "Havin'im, sana olan sevgim, denizlerin derinliği kadar sonsuz.",
        "Havin'im, saçlarının arasına dokunduğumda hissettiğim mutluluk anlatılamaz.",
        "Havin'im, seninle izlediğimiz günbatımları hayatımın en değerli tabloları.",
        "Havin'im, sesini duyduğumda kalbim hızlanıyor, nefesim kesiliyor.",
        "Havin'im, sana sarıldığım her an, tüm dertlerimi unutuyorum.",
        "Havin'im, senin yanında olmak benim için her zaman bir mucize.",
        "Havin'im, senin aşkın hayatıma anlam katan en derin duygu.",
        "Havin'im, seninle geçirdiğim her dakika, yaşadığım en büyük zenginlik.",
        "Havin'im, kirpiklerinin arasından baktığında dünyamı aydınlatıyorsun.",
        "Havin'im, ismini fısıldadığımda tüylerim diken diken oluyor.",
        "Havin'im, bana dokunduğun her an elektrikleniyorum, kalbim duracak gibi oluyor.",
        "Havin'im, seninle kitap okurken paylaştığımız sessizlik, en sevdiğim melodilerden.",
        "Havin'im, seni her düşündüğümde yüzümde beliren gülümsemeyi silemiyorum.",
        "Havin'im, rüyalarımda bile seni görmek için sabırsızlanıyorum.",
        "Havin'im, senin gözlerindeki derinlik, keşfetmek istediğim sonsuz bir okyanus.",
        "Havin'im, seninle ilk öpüşmemiz hayatımın en unutulmaz anlarından biri.",
        "Havin'im, senin yanında olmak, tüm streslerimi unuttuğum bir terapi gibi.",
        "Havin'im, senin için yazdığım her şiirde kalbimin atışlarını duyabilirsin.",
        "Havin'im, seni düşündüğümde zamanın nasıl geçtiğini anlamıyorum.",
        "Havin'im, senin adını her söylediğimde içimde binlerce kelebek uçuşuyor.",
        "Havin'im, teninin yumuşaklığı bana huzurun anlamını öğretti.",
        "Havin'im, seninle izlediğimiz yıldızlı geceler hayatımın en romantik anları.",
        "Havin'im, seni özlediğimde yazdığım her satır, kalbimin sana seslenişi.",
        "Havin'im, sana olan aşkım her gün daha da derinleşiyor ve büyüyor.",
        "Havin'im, senin yanında olmadığım her an eksiklik hissediyorum.",
        "Havin'im, beraber dinlediğimiz şarkılar artık sadece bize ait.",
        "Havin'im, sana olan sevgimi ifade eden kelimeler henüz icat edilmedi.",
        "Havin'im, seninle hayallerimizi paylaşmak en büyük zenginliğim.",
        "Havin'im, saçlarını okşarken hissettiğim mutluluk tarif edilemez.",
        "Havin'im, bana gülümsediğin her an, dünyamı aydınlatıyorsun.",
        "Havin'im, seninle konuşurken geçen saatler, hayatımın en değerli zamanları.",
        "Havin'im, kokunu hissettiğimde kendimi evimde gibi hissediyorum.",
        "Havin'im, senin sıcaklığını hissetmek, hayatın en büyük armağanı.",
        "Havin'im, seninle paylaştığımız kahkahaların sesini kalbimde saklıyorum.",
        "Havin'im, beraber izlediğimiz filmlerin hiçbir sahnesini kaçırmak istemiyorum.",
        "Havin'im, senin yanında olmak, cennetin yeryüzündeki hali.",
        "Havin'im, gözlerinin derinliğinde kaybolmak en büyük tutkum.",
        "Havin'im, seni ilk gördüğüm anın heyecanını hala içimde taşıyorum.",
        "Havin'im, seninle geçirdiğim her anın hatırası kalbime kazınmış durumda.",
        "Havin'im, sana sarıldığımda dünyanın tüm güzellikleri bir araya geliyor gibi.",
        "Havin'im, seni her düşündüğümde yüreğimde hissettiğim mutluluk anlatılamaz.",
        "Havin'im, seninle olmak hayatın bana verdiği en güzel hediye.",
        "Havin'im, sesini duyduğumda hissettiğim huzuru başka hiçbir yerde bulamıyorum.",
        "Havin'im, seninle paylaştığımız kahvaltılar günümün en güzel başlangıcı.",
        "Havin'im, senin bakışlarının büyüsünde kaybolmak en büyük arzum.",
        "Havin'im, sana yazdığım her mesajda kalbimin bir parçasını gönderiyorum.",
        "Havin'im, seninle geçirdiğim geceler hayatımın en değerli saatleri.",
        "Havin'im, senin yanındayken zaman duruyor, anlar uzuyor gibi hissediyorum.",
        "Havin'im, seni her gördüğümde ilk kez âşık oluyormuş gibi heyecanlanıyorum.",
        "Havin'im, senin parfümünün kokusu benim için dünyanın en güzel kokusu.",
        "Havin'im, ellerini ellerimde tuttuğumda hissettiğim huzur anlatılamaz.",
        "Havin'im, seninle şehir şehir gezmek ve yeni anılar biriktirmek istiyorum.",
        "Havin'im, sana sarıldığımda dünyanın tüm sorunları uçup gidiyor.",
        "Havin'im, senin kahkahanı duymak için her şeyi yapardım.",
        "Havin'im, seninle birlikte yaşayacağımız gelecek için her gün heyecanlanıyorum.",
        "Havin'im, seni özlediğimde kalbim adeta yerinden çıkacakmış gibi oluyor.",
        "Havin'im, sana olan sevgimi anlatmak için tüm hayatım yetmez.",
        "Havin'im, seninle izlediğimiz her gün batımı, hayatımın en romantik anları.",
        "Havin'im, senin varlığın hayatımdaki en büyük mutluluk kaynağı.",
        "Havin'im, bana öğrettiğin sevgi, hayatımın en değerli dersi.",
        "Havin'im, seni tanıdığım gün hayatımın dönüm noktasıydı.",
        "Havin'im, gözlerindeki ışıltı, karanlık gecelerimde yolumu aydınlatan fener.",
        "Havin'im, seninle paylaştığım her sır, aramızdaki bağı daha da güçlendiriyor.",
        "Havin'im, seni görünce hissettiğim heyecan hiç azalmıyor.",
        "Havin'im, senin sevgin hayatımın en büyük motivasyonu.",
        "Havin'im, seninle paylaştığım her anı kalbimde bir hazine gibi saklıyorum.",
        "Havin'im, bana verdiğin değer için her gün şükrediyorum.",
        "Havin'im, sen benim hayatımın anlamı, varlığımın nedenisin.",
        "Havin'im, seninle birlikte uyumak ve uyanmak en büyük dileğim.",
        "Havin'im, senin yanında kendimi tamamlanmış hissediyorum.",
        "Havin'im, sana olan aşkımı ifade eden kelimeler henüz keşfedilmedi.",
        "Havin'im, seninle birlikte yaşlanmak ve anılarımızı paylaşmak istiyorum.",
        "Havin'im, sana baktığımda gördüğüm sevgi, benim en büyük zenginliğim.",
        "Havin'im, seninle müzik dinlerken hissettiğim bağ, anlatılamaz derecede derin.",
        "Havin'im, her sabah gözlerini açtığında yanında olmak istiyorum.",
        "Havin'im, sana dokunduğumda hissettiğim elektriklenme hala ilk günkü gibi.",
        "Havin'im, göz göze geldiğimiz o ilk an, hayatımın en büyülü anıydı.",
        "Havin'im, senin yanında kendimi dünyanın en şanslı insanı gibi hissediyorum.",
        "Havin'im, seninle paylaştığım her damla gözyaşı ve kahkaha, hayatımın özeti gibi.",
        "Havin'im, sana yazdığım her aşk mektubu, kalbimin en derin köşesinden geliyor.",
        "Havin'im, seninle birlikte nefes almak, yaşadığımı hissetmenin en güzel yolu.",
        "Havin'im, senin sevgin hayatımın her anını değerli kılıyor.",
        "Havin'im, seni her düşündüğümde kalbimde bir şölen başlıyor.",
        "Havin'im, seninle birlikte yaşadığım her an, hayatımın film şeridi gibi gözümün önünden geçiyor.",
        "Havin'im, senin adını söylemek bile dudaklarımı tatlandırıyor.",
        "Havin'im, sana olan aşkım, zamanın ve mekanın ötesinde sonsuz bir duygu.",
        "Havin'im, seninle izlediğimiz yıldızlar, bizim gizli şahitlerimiz gibi.",
        "Havin'im, senin yanında olduğum her an, hayatın tüm güzelliklerini yaşıyorum.",
        "Havin'im, sana sarıldığımda dünyanın tüm dertlerinden uzaklaşıyorum.",
        "Havin'im, senin gülümsemen benim için en değerli mücevherden daha kıymetli.",
        "Havin'im, seninle paylaştığımız sessizlikler bile anlamlı.",
        "Havin'im, sana duyduğum aşk her geçen gün daha da derinleşiyor.",
        "Havin'im, senin sesini duymak günümü aydınlatan en güzel şey.",
        "Havin'im, seninle el ele tutuşmak, kalbimin hızla atmasına neden oluyor.",
        "Havin'im, seni düşünmek bile beni mutlu etmeye yetiyor.",
        "Havin'im, senin varlığın hayatımın en büyük şansı.",
        "Havin'im, sana olan sevgim, yıldızların sayısından daha fazla.",
        "Havin'im, seninle paylaştığım her an, hayatımın en değerli parçası.",
        "Havin'im, sensiz bir hayat düşünmek bile imkansız.",
        "Havin'im, sana olan aşkım her gün katlanarak büyüyor.",
        "Havin'im, seninle yaşadığım her aşk hikayesi, benim en sevdiğim roman.",
        "Havin'im, seni gördüğümde zamanın durduğunu hissediyorum.",
        "Havin'im, senin yanında olduğum her an, hayatın tüm güzelliklerini yaşıyorum.",
        "Havin'im, sana olan tutkum, sözcüklerle anlatılamayacak kadar derin.",
        "Havin'im, sensiz geçen her gün, eksik bir hayat gibi.",
        "Havin'im, sana olan sevgim, güneşin doğuşu gibi her gün yenileniyor.",
        "Havin'im, seninle paylaştığım her gülüş, hayatımın en değerli hazinesi.",
        "Havin'im, senin yanında kendimi tamamlanmış hissediyorum.",
        "Havin'im, sana olan aşkım, zamanın ötesinde sonsuza dek sürecek.",
        "Havin'im, seninle birlikte geçirdiğim her an, hayatımın en anlamlı zamanı.",
        "Havin'im, senin sevgin beni her gün yeniden hayata bağlıyor.",
        "Havin'im, sana dokunduğumda hissettiğim mutluluk, tarif edilemez.",
        "Havin'im, seni düşünmek bile kalbimi heyecanla dolduruyor.",
        "Havin'im, senin yanında olmak, cennetin yeryüzündeki hali.",
        "Havin'im, sana olan sevgimi anlatmak için kelimeler yetersiz kalıyor.",
        "Havin'im, seninle birlikte gülmek, hayatın en büyük armağanı.",
        "Havin'im, sensiz bir hayat, renksiz bir tablo gibi.",
        "Havin'im, sana olan aşkım her geçen gün daha da güçleniyor.",
        "Havin'im, seninle paylaştığım her anı, kalbimde bir hazine gibi saklıyorum.",
        "Havin'im, senin varlığın hayatımın en büyük mutluluk kaynağı.",
        "Havin'im, sana olan sevgim, denizlerin derinliği kadar sonsuz.",
        "Havin'im, seninle geçen her gün, hayatımın en değerli hediyesi.",
        "Havin'im, sensiz bir dünya düşünemiyorum.",
        "Havin'im, sana olan aşkım, her gün yeniden filizleniyor.",
        "Havin'im, seninle paylaştığım her kahkaha, hayatımın en değerli sesi.",
        "Havin'im, senin yanında olduğum her an, kendimi tam hissediyorum.",
        "Havin'im, sana olan sevgim, zamanın ve mekanın ötesinde.",
        "Havin'im, seninle yaşadığım her an, hayatımın film şeridi gibi gözümün önünden geçiyor.",
        "Havin'im, senin sevgin, hayatımın en büyük motivasyonu.",
        "Havin'im, sana dokunduğumda hissettiğim enerji, beni canlandırıyor.",
        "Havin'im, seni düşünmek bile beni mutlu etmeye yetiyor.",
        "Havin'im, senin yanında olmak, dünyanın en huzurlu yeri.",
        "Havin'im, sana olan sevgimi anlatmak için tüm hayatım yetmez.",
        "Havin'im, seninle birlikte gülmek, hayatın en güzel melodisi.",
        "Havin'im, sensiz bir hayat, eksik bir şarkı gibi.",
        "Havin'im, sana olan aşkım, her gün daha da derinleşiyor.",
        "Havin'im, seninle paylaştığım her anı, kalbimde bir mücevher gibi saklıyorum.",
        "Havin'im, senin varlığın hayatımın en büyük zenginliği.",
        "Havin'im, sana olan sevgim, yıldızların parlaklığı kadar sonsuz.",
        "Havin'im, seninle geçirdiğim her an, hayatımın en değerli zamanı.",
        "Havin'im, sensiz bir dünya, benim için anlamsız.",
        "Havin'im, sana olan aşkım, her sabah güneşle birlikte yeniden doğuyor.",
        "Havin'im, seninle paylaştığım her söz, kalbimin derinliklerinden geliyor.",
        "Havin'im, senin yanında olduğum her an, kendimi evimde hissediyorum.",
        "Havin'im, sana olan sevgim, zamanın ötesine uzanıyor.",
        "Havin'im, seninle geçirdiğim her anın hatırası, kalbime kazınmış durumda.",
        "Havin'im, senin sevgin, hayatımın en büyük şansı.",
        "Havin'im, sana sarıldığımda hissettiğim huzur, anlatılamaz derecede derin.",
        "Havin'im, seni düşündüğümde içimi kaplayan sıcaklık, en büyük mutluluk kaynağım.",
        "Havin'im, senin yanında olmak, dünyanın en güzel duygusu.",
        "Havin'im, sana olan sevgim, her geçen gün daha da büyüyor.",
        "Havin'im, seninle paylaştığım her dakika, hayatımın en değerli parçası.",
        "Havin'im, sensiz bir hayat, çölde susuz kalmak gibi.",
        "Havin'im, sana olan aşkım, her gün yeniden keşfedilmeyi bekliyor.",
        "Havin'im, seninle yaşadığım her an, hayatımın en büyük hazinesi.",
        "Havin'im, senin varlığın, benim en büyük şansım.",
        "Havin'im, sana olan sevgim, okyanus kadar derin ve sonsuz.",
        "Havin'im, seninle geçirdiğim her saniye, yaşamaya değer.",
        "Havin'im, sensiz bir dünya, benim için düşünülemez.",
        "Havin'im, sana olan aşkım, her gün biraz daha güçleniyor.",
        "Havin'im, seninle paylaştığım her gülümseme, hayatımın en değerli resmi.",
        "Havin'im, senin yanında olduğum her an, cennetin bir parçası gibi.",
        "Havin'im, sana olan sevgim, hiçbir sınır tanımıyor.",
        "Havin'im, seninle olan her anımız, hayatımın en özel saatleri.",
        "Havin'im, senin sevgin, beni ben yapan en önemli duygu.",
        "Havin'im, sana dokunduğumda hissettiğim sıcaklık, beni hayata bağlıyor.",
        "Havin'im, seni düşünmek bile kalbimi sevinçle dolduruyor.",
        "Havin'im, senin yanında olmak, dünyanın en büyük lütfu.",
        "Havin'im, sana olan sevgimi anlatacak kelimeler henüz icat edilmedi.",
        "Havin'im, seninle birlikte gülmek, hayatın en büyük keyfi.",
        "Havin'im, sensiz bir hayat, benim için düşünülemez bile.",
        "Havin'im, sana olan aşkım, her geçen gün daha da derinleşiyor.",
        "Havin'im, seninle paylaştığım her an, hayatımın en değerli parçası.",
        "Havin'im, senin varlığın, benim en büyük mutluluk kaynağım.",
        "Havin'im, sana olan sevgim, gökyüzündeki yıldızlar kadar sonsuz.",
        "Havin'im, seninle geçirdiğim her dakika, yaşamın anlamını yeniden keşfetmek gibi.",
        "Havin'im, sensiz bir dünya, eksik bir bulmaca gibi.",
        "Havin'im, sana olan aşkım, her sabah yeniden uyanıyor.",
        "Havin'im, seninle yaşadığım her an, kalbimde sonsuza dek yaşayacak.",
        "Havin'im, senin yanında olmak, kendimi bulduğum yer.",
        "Havin'im, sana olan sevgim, zamanın ve mekanın ötesinde bir duygu.",
        "Havin'im, seninle paylaştığım her söz, kalbimin en derinliklerinden geliyor.",
        "Havin'im, senin sevgin, hayatımın en büyük armağanı.",
        "Havin'im, sana sarıldığımda hissettiğim huzur, dünyada eşi benzeri olmayan bir his.",
        "Havin'im, seni düşündüğümde içimde oluşan sıcaklık, en büyük mutluluk kaynağım.",
        "Havin'im, senin yanında olmak, hayatın bana verdiği en büyük hediye.",
        "Havin'im, sana olan sevgim, her geçen gün daha da güçleniyor.",
        "Havin'im, seninle geçirdiğim her an, hayatımın en değerli zamanı.",
        "Havin'im, sensiz bir hayat, renksiz bir resim gibi.",
        "Havin'im, sana olan aşkım, her gün yeniden filizleniyor.",
        "Havin'im, seninle paylaştığım her kahkaha, kalbimde sonsuza dek yaşayacak.",
        "Havin'im, senin varlığın, hayatımın en büyük zenginliği.",
        "Havin'im, sana olan sevgim, dünyadaki tüm okyanuslardann daha derin.",
        "Havin'im, seninle geçirdiğim her saniye, yaşamın anlamını yeniden keşfetmek gibi.",
        "Havin'im, sensiz bir dünya, benim için düşünülemez bile.",
        "Havin'im, sana olan aşkım, her gün kendini yeniliyor.",
        "Havin'im, seninle yaşadığım her an, hayatımın en değerli hazinesi.",
        "Havin'im, senin yanında olmak, kendimi tam hissettiğim tek yer.",
        "Havin'im, sana olan sevgim, hiçbir sınır tanımıyor.",
        "Havin'im, seninle paylaştığım her an, kalbimde sonsuza dek yaşayacak.",
        "Havin'im, senin sevgin, beni hayata bağlayan en güçlü ip.",
        "Havin'im, sana dokunduğumda hissettiğim mutluluk, tarif edilemez.",
        "Havin'im, seni düşünmek bile kalbimi heyecanla dolduruyor.",
        "Havin'im, senin yanında olmak, dünyanın en güzel duygusu.",
        "Havin'im, sana olan sevgimi anlatmak için kelimeler yetersiz kalıyor.",
        "Havin'im, seninle birlikte gülmek, hayatın en büyük armağanı.",
        "Havin'im, sensiz bir hayat, oksijensiz kalmak gibi.",
        "Havin'im, sana olan aşkım, her geçen gün daha da derinleşiyor.",
        "Havin'im, seninle geçirdiğim her an, hayatımın en değerli parçası.",
        "Havin'im, senin varlığın, benim en büyük şansım.",
        "Havin'im, sana olan sevgim, güneşin sıcaklığı kadar içten ve güçlü.",
        "Havin'im, seninle geçirdiğim her dakika, yaşamın anlamını yeniden keşfetmek gibi.",
        "Havin'im, sensiz bir dünya, eksik bir şarkı gibi.",
        "Havin'im, sana olan aşkım, her sabah güneşle birlikte yeniden doğuyor.",
        "Havin'im, seninle paylaştığım her söz, kalbimin sesi.",
        "Havin'im, senin yanında olmak, kendimi evimde hissetmek gibi.",
        "Havin'im, sana olan sevgim, zamanın ve mekanın ötesinde bir duygu.",
        "Havin'im, seninle yaşadığım her an, hayatımın film şeridi gibi gözümün önünden geçiyor.",
        "Havin'im, senin sevgin, hayatımın en büyük motivasyonu.",
        "Havin'im, sana sarıldığımda hissettiğim huzur, dünyada eşi benzeri olmayan bir his.",
        "Havin'im, seni düşündüğümde içimde oluşan sıcaklık, en büyük mutluluk kaynağım.",
        "Havin'im, senin yanında olmak, hayatin bana verdiği en büyük hediye.",
        "Havin'im, sana olan sevgim, her geçen gün daha da güçleniyor.",
        "Havin'im, seninle geçirdiğim her an, yaşadığıma değer kılıyor.",
        "Havin'im, sensiz bir hayat, benim için eksik bir puzzle gibi.",
        "Havin'im, sana olan aşkım, her gün kendini yeniliyor.",
        "Havin'im, seninle paylaştığım her kahkaha, hayatımın en değerli sesi.",
        "Havin'im, senin varlığın, benim en büyük mutluluk kaynağım.",
        "Havin'im, sana olan sevgim, gökyüzündeki yıldızlar kadar sonsuz.",
        "Havin'im, seninle geçirdiğim her saniye, zamanın durduğu anlar gibi.",
        "Havin'im, sensiz bir dünya, benim için anlamsız ve boş.",
        "Havin'im, sana olan aşkım, her gün daha da derinleşen bir okyanus gibi.",
        "Havin'im, seninle yaşadığım her an, kalbimde sonsuza dek yaşayacak bir anı.",
        "Havin'im, senin yanında olmak, dünyanın en huzurlu yerinde olmak gibi.",
        "Havin'im, sana olan sevgim, hiçbir sınır tanımayan bir duygu.",
        "Havin'im, seninle geçirdiğim her an, hayatımın en değerli hazinesi.",
        "Havin'im, senin sevgin, beni hayata bağlayan en güçlü bağ.",
        "Havin'im, sana dokunduğumda hissettiğim enerji, beni canlandırıyor.",
        "Havin'im, seni düşünmek bile kalbimi heyecanla dolduruyor.",
        "Havin'im, senin yanında olmak, cennetin yeryüzündeki hali.",
        "Havin'im, sana olan sevgimi anlatmak için tüm dünya dilleri yetersiz kalır.",
        "Havin'im, seninle birlikte gülmek, hayatın en büyük mutluluğu.",
        "Havin'im, sensiz bir hayat, benim için düşünülemez bile.",
        "Havin'im, sana olan aşkım, her geçen gün daha da büyüyor.",
        "Havin'im, seninle paylaştığım her an, hayatımın en değerli parçası.",
        "Havin'im, senin varlığın, benim en büyük şansım.",
        "Havin'im, sana olan sevgim, gökyüzündeki yıldızlar kadar sonsuz.",
        "Havin'im, seninle geçirdiğim her dakika, yaşamın anlamını yeniden keşfetmek gibi.",
        "Havin'im, sensiz bir dünya, eksik bir resim gibi.",
        "Havin'im, sana olan aşkım, her sabah yeniden doğan güneş gibi taze.",
        "Havin'im, seninle paylaştığım her söz, kalbimin derinliklerinden geliyor.",
        "Havin'im, senin yanında olmak, kendimi tam hissettiğim tek yer.",
        "Havin'im, sana olan sevgim, zamanın ve mekanın ötesinde bir duygu.",
        "Havin'im, seninle yaşadığım her an, hayatımın film şeridi gibi gözümün önünden geçiyor.",
        "Havin'im, senin sevgin, hayatımın en büyük motivasyonu.",
        "Havin'im, sana sarıldığımda hissettiğim huzur, dünyada eşi benzeri olmayan bir his.",
        "Havin'im, seni düşündüğümde içimde oluşan sıcaklık, en büyük mutluluk kaynağım.",
        "Havin'im, senin yanında olmak, hayatın bana verdiği en büyük lütuf.",
        "Havin'im, sana olan sevgim, her geçen gün daha da güçleniyor.",
        "Havin'im, seninle geçirdiğim her an, yaşadığıma değer kılıyor.",
        "Havin'im, sensiz bir hayat, çölde susuz kalmak gibi.",
        "Havin'im, sana olan aşkım, her gün yenilenen bir mucize gibi.",
        "Havin'im, seninle paylaştığım her kahkaha, hayatımın en değerli anıları.",
        "Havin'im, senin varlığın, benim en büyük mutluluk kaynağım.",
        "Havin'im, sana olan sevgim, denizin derinliği kadar sonsuz.",
        "Havin'im, seninle geçirdiğim her saniye, zamanın durduğu anlar gibi.",
        "Havin'im, sensiz bir dünya, benim için düşünülemez.",
        "Havin'im, sana olan aşkım, her gün daha da derinleşen bir duygu.",
        "Havin'im, seninle yaşadığım her an, kalbimde sonsuza dek yaşayacak.",
        "Havin'im, senin yanında olmak, dünyanın en huzurlu yerinde olmak gibi.",
        "Havin'im, sana olan sevgim, hiçbir sınır tanımayan bir duygu.",
        "Havin'im, seninle geçirdiğim her an, hayatımın en değerli parçası.",
        "Havin'im, senin sevgin, beni hayata bağlayan en güçlü bağ.",
        "Havin'im, sana dokunduğumda hissettiğim mutluluk, tarif edilemez.",
        "Havin'im, seni düşünmek bile kalbimi heyecanla dolduruyor.",
        "Havin'im, senin yanında olmak, dünyanın en güzel duygusu.",
        "Havin'im, sana olan sevgimi anlatmak için kelimeler yetersiz kalıyor.",
        "Havin'im, seninle birlikte gülmek, hayatın en büyük keyfi.",
        "Havin'im, sensiz bir hayat, oksijensiz kalmak gibi.",
        "Havin'im, sana olan aşkım, her geçen gün daha da derinleşiyor.",
        "Havin'im, seninle paylaştığım her an, hayatımın en değerli hazinesi.",
        "Havin'im, senin varlığın, benim en büyük şansım.",
        "Havin'im, sana olan sevgim, güneşin sıcaklığı kadar içten ve güçlü.",
        "Havin'im, seninle geçirdiğim her dakika, yaşamın anlamını yeniden keşfetmek gibi.",
        "Havin'im, sensiz bir dünya, eksik bir şarkı gibi.",
        "Havin'im, sana olan aşkım, her sabah güneşle birlikte yeniden doğuyor.",
        "Havin'im, seninle yaşadığım her an, kalbimde bir hazine gibi saklıyorum.",
        "Havin'im, senin yanında olmak, kendimi evimde hissetmek gibi.",
        "Havin'im, sana olan sevgim, zamanın ve mekanın ötesinde bir duygu.",
        "Havin'im, seninle birlikte her anım, hayatımın film şeridi gibi gözümün önünden geçiyor.",
        "Havin'im, senin sevgin, hayatımın en büyük motivasyonu.",
        "Havin'im, sana sarıldığımda hissettiğim huzur, dünyada eşi benzeri olmayan bir his.",
        "Havin'im, seni düşündüğümde içimde oluşan sıcaklık, en büyük mutluluk kaynağım.",
        "Havin'im, senin yanında olmak, hayatın bana verdiği en büyük hediye.",
        "Havin'im, sana olan sevgim, her geçen gün daha da güçleniyor.",
        "Havin'im, seninle geçirdiğim her an, yaşama olan inancımı pekiştiriyor.",
        "Havin'im, sensiz bir hayat, benim için düşünülemez bile.",
        "Havin'im, sana olan aşkım, her gün kendini yenileyen bir mucize.",
        "Havin'im, seninle paylaştığım her kahkaha, hayatımın en değerli sesi.",
        "Havin'im, senin varlığın, benim en büyük mutluluk kaynağım.",
        "Havin'im, sana olan sevgim, gökyüzündeki yıldızlar kadar sonsuz.",
        "Havin'im, seninle geçirdiğim her saniye, zamanın durduğu ve sadece aşkın konuştuğu anlar.",
        
        // 210 Ek Romantik Aşk Mesajı (Toplam 1000 mesaj için)
        "Havin'im, hayatımın her anında senin sevgin beni sarıp sarmalıyor.",
        "Havin'im, bir gülüşünle tüm kötü düşüncelerim uçup gidiyor.",
        "Havin'im, senin yanında olmak dünyanın en büyük lütfu.",
        "Havin'im, gözlerindeki aşk ateşi kalbimi yakıyor.",
        "Havin'im, seninle paylaştığım her söz kutsal bir yemin gibi.",
        "Havin'im, sana olan sevgim her gün yeni bir çiçek gibi açıyor.",
        "Havin'im, ismini her söylediğimde kalbim kanatlanıyor.",
        "Havin'im, sesinin melodisi kulaklarımda çınlayan en güzel müzik.",
        "Havin'im, seninle geçirdiğim her an hayatımın en değerli mücevheri.",
        "Havin'im, seni düşünmek bile bana sonsuz mutluluk veriyor.",
        "Havin'im, seninle baş başa geçirdiğimiz her dakika paha biçilemez.",
        "Havin'im, kokunu içime çektiğimde huzurla doluyorum.",
        "Havin'im, her fotoğrafta gözlerim önce seni arıyor.",
        "Havin'im, sen olmadan geçen her an eksik ve anlamsız.",
        "Havin'im, ellerinin sıcaklığı tüm soğukluğumu alıp götürüyor.",
        "Havin'im, her sabah senin adınla uyanmak en büyük mutluluğum.",
        "Havin'im, sensiz bir hayat düşünemiyorum bile.",
        "Havin'im, birlikte izlediğimiz gün batımları ruhumun gıdası.",
        "Havin'im, gülüşünün ışığı karanlık günlerimi aydınlatıyor.",
        "Havin'im, seninle paylaştığım her sır aramızdaki bağı güçlendiriyor.",
        "Havin'im, yanımda olmadığın her an özlemle doluyorum.",
        "Havin'im, seni sevmek nefes almak kadar doğal ve vazgeçilmez.",
        "Havin'im, senin dokunuşun tenimde bıraktığı iz silinmiyor.",
        "Havin'im, her mesajın kalbimde yeni bir kapı açıyor.",
        "Havin'im, seni düşünmeden geçen tek bir anım bile yok.",
        "Havin'im, seninle dans etmek yıldızlarla vals yapmak gibi.",
        "Havin'im, senin varlığın hayatımın en büyük şansı.",
        "Havin'im, gökyüzündeki tüm yıldızlar senin gözlerinde toplanmış.",
        "Havin'im, hayatımın her anlamı senin sevginde gizli.",
        "Havin'im, seni sevmek hayattaki en doğru kararım.",
        "Havin'im, adını fısıldamak bile tüylerimi diken diken ediyor.",
        "Havin'im, sana olan sevgim her gün katlanarak büyüyor.",
        "Havin'im, senin yanında olmak cennetin yeryüzündeki hali.",
        "Havin'im, seninle birlikte zamanın nasıl geçtiğini anlamıyorum.",
        "Havin'im, her akşam seni düşünerek uykuya dalıyorum.",
        "Havin'im, sesinin tınısı kulaklarımda çınlayan en güzel melodi.",
        "Havin'im, sana sarılmak dünyadaki tüm dertlerimi unutturuyor.",
        "Havin'im, seni her düşündüğümde kalbim delice çarpıyor.",
        "Havin'im, aşkımız her geçen gün daha da güçleniyor.",
        "Havin'im, gözlerindeki parıltı geleceğimizin aydınlığı.",
        "Havin'im, seninle paylaştığım her an ömrüme ömür katıyor.",
        "Havin'im, saçlarını okşarken hissettiğim mutluluk tarif edilemez.",
        "Havin'im, kalbim sadece senin adınla atıyor.",
        "Havin'im, senin bir gülüşün tüm kötü günlerimi unutturuyor.",
        "Havin'im, hayallerimde her zaman sen varsın.",
        "Havin'im, sana olan aşkımı anlatacak kelimeler henüz icat edilmedi.",
        "Havin'im, seninle birlikte yaşlanmak en büyük dileğim.",
        "Havin'im, her nefesimde senin kokunu hissetmek istiyorum.",
        "Havin'im, sen benim hayattaki en büyük şansımsın.",
        "Havin'im, seni düşündüğümde yüzümde beliren gülümsemeyi silemiyorum.",
        "Havin'im, senin yanında kendimi evimde hissediyorum.",
        "Havin'im, sana olan sevgim her gün daha da derinleşiyor.",
        "Havin'im, ellerini ellerimde tutmak dünyanın en güzel duygusu.",
        "Havin'im, sensiz geçen her an ruhumu eksik bırakıyor.",
        "Havin'im, gözlerine her baktığımda ilk günkü heyecanı yaşıyorum.",
        "Havin'im, seninle aynı havayı solumak bile mutluluk veriyor.",
        "Havin'im, yanında olmadığım her an seni özlüyorum.",
        "Havin'im, sana olan aşkım zamanla daha da büyüyor.",
        "Havin'im, seninle paylaştığım her anı kalbimde saklıyorum.",
        "Havin'im, adını her duyduğumda kalbim hızla atmaya başlıyor.",
        "Havin'im, senin yanında olmak hayatın en güzel hediyesi.",
        "Havin'im, seni sevmek hayatımın en anlamlı serüveni.",
        "Havin'im, beraber yürüdüğümüz her yol benim için özel.",
        "Havin'im, senin kahkahan dünyadaki en güzel ses.",
        "Havin'im, seninle birlikte olmak hayatımın amacı.",
        "Havin'im, sana dokunduğumda hissettiğim elektriklenme ilk günkü gibi taze.",
        "Havin'im, senin varlığın hayatımın anlamı.",
        "Havin'im, birlikte uyandığımız her sabah yeni bir başlangıç.",
        "Havin'im, gözlerindeki sevgi okyanusu kalbimi ısıtıyor.",
        "Havin'im, senden başka kimseyi düşünemiyorum.",
        "Havin'im, senin için yazdığım her şiir kalbimin sesi.",
        "Havin'im, seni sevmek hayatımın en doğal eylemi.",
        "Havin'im, seninle geçirdiğim her an ömrümün en değerli zamanı.",
        "Havin'im, kokun hafızama öyle işlemiş ki, her an yanımdasın.",
        "Havin'im, sana olan sevgim her gün kendini yeniliyor.",
        "Havin'im, seni görür görmez tüm sıkıntılarım uçup gidiyor.",
        "Havin'im, seninle birlikte yaşamak en büyük hayalim.",
        "Havin'im, gözlerindeki ışık hayatımı aydınlatıyor.",
        "Havin'im, sana olan aşkım her geçen gün daha da derinleşiyor.",
        "Havin'im, senin yanında olmak huzurun tanımı.",
        "Havin'im, birlikte çıktığımız her yolculuk hayatımızın hikayesi.",
        "Havin'im, seni düşünmek bile kalbimi hızlandırıyor.",
        "Havin'im, sana olan sevgimi kelimelere dökmek imkansız.",
        "Havin'im, seninle paylaştığım her kahkaha hayatımın en değerli sesi.",
        "Havin'im, senin varlığın hayatımın en büyük armağanı.",
        "Havin'im, seni tanıdığım gün hayatımın dönüm noktasıydı.",
        "Havin'im, sana olan aşkımı her gün daha derinden hissediyorum.",
        "Havin'im, seninle el ele yürümek hayatın en güzel yanı.",
        "Havin'im, senden uzakta geçen her dakika bir ömür gibi.",
        "Havin'im, gözlerinin derinliğinde kaybolmak istiyorum.",
        "Havin'im, senin sevginle her gün yeniden doğuyorum.",
        "Havin'im, sana olan bağlılığım her geçen gün artıyor.",
        "Havin'im, seninle birlikte nefes almak bile özel.",
        "Havin'im, senin dokunuşun benim için bir mucize gibi.",
        "Havin'im, seni her düşündüğümde yüreğim titriyor.",
        "Havin'im, aşkımızın hikayesi hiç bitmeyecek bir roman.",
        "Havin'im, yanında olmadığım her an içimde bir eksiklik hissediyorum.",
        "Havin'im, seni sevmek hayatımın en anlamlı eylemi.",
        "Havin'im, seninle paylaştığım her söz kalbimin derinliklerinden geliyor.",
        "Havin'im, senin varlığın hayatımın merkezi.",
        "Havin'im, sana olan aşkım her geçen gün büyüyor.",
        "Havin'im, birlikte ıslandığımız yağmurlar hayatımın en güzel anıları.",
        "Havin'im, gözlerindeki sevgi dünyadaki en değerli hazine.",
        "Havin'im, sensiz bir hayat düşünemiyorum bile.",
        "Havin'im, seni sevmek nefes almak kadar doğal.",
        "Havin'im, seninle kurduğum her hayalin gerçekleşmesini istiyorum.",
        "Havin'im, sana olan sevgim her geçen gün daha da güçleniyor.",
        "Havin'im, seni tanıdığım için kendimi çok şanslı hissediyorum.",
        "Havin'im, seninle birlikte geçirdiğim her an hayatımın en değerli zamanı.",
        "Havin'im, gözlerinde gördüğüm sevgi beni hayata bağlıyor.",
        "Havin'im, sana her baktığımda kalbim duracak gibi oluyor.",
        "Havin'im, seninle birlikte büyüyen aşkımız hayatımın en büyük zenginliği.",
        "Havin'im, seni düşünmek gününün en güzel anı.",
        "Havin'im, sana olan sevgim hiçbir zaman azalmayacak.",
        "Havin'im, seninle paylaştığım her anın hatırası kalbime kazınmış durumda.",
        "Havin'im, sesini duymak günümün en mutlu anı.",
        "Havin'im, sana sarılmak huzurun tanımı.",
        "Havin'im, sana olan aşkım her nefesimde büyüyor.",
        "Havin'im, birlikte yaşlandığımızı hayal etmek bile beni mutlu ediyor.",
        "Havin'im, gözlerindeki o bakış beni derinden etkiliyor.",
        "Havin'im, senin yanındayken zaman duruyor sanki.",
        "Havin'im, seni sevmek hayatımın en güzel serüveni.",
        "Havin'im, seninle paylaştığım her kahve, her çay hayatımın tadı.",
        "Havin'im, senin varlığın hayatımın anlamı.",
        "Havin'im, sana olan aşkımı tarif etmek mümkün değil.",
        "Havin'im, hayatımda olduğun için her gün şükrediyorum.",
        "Havin'im, seninle elele geçirdiğimiz her an paha biçilemez.",
        "Havin'im, seni düşünmek bile beni heyecanlandırıyor.",
        "Havin'im, sana olan sevgimi anlatmaya kelimeler yetmez.",
        "Havin'im, seninle birlikte yaşadığım her an hayatımın en güzel hediyesi.",
        "Havin'im, gözlerindeki ışıltı geleceğimizi aydınlatıyor.",
        "Havin'im, senin yanında olmak cennetin yeryüzündeki hali.",
        "Havin'im, sana olan sevgim her gün yeniden filizleniyor.",
        "Havin'im, seninle paylaştığım her nefes benim için çok değerli.",
        "Havin'im, adını her duyduğumda kalbim hızlanıyor.",
        "Havin'im, seni seviyorum demenin bin farklı yolunu biliyorum.",
        "Havin'im, varlığın hayatımın en büyük şansı.",
        "Havin'im, aşkımız her gün daha da derinleşiyor.",
        "Havin'im, seninle yan yana olmak hayatın en güzel yanı.",
        "Havin'im, seni tanıdığım an hayatımın en güzel anıydı.",
        "Havin'im, sana duyduğum sevgi her geçen gün büyüyor.",
        "Havin'im, hayatımda olduğun için çok şanslıyım.",
        "Havin'im, seni sevmek hayatımın amacı.",
        "Havin'im, kalbim seninle dolduğunda dünyanın en mutlu insanı oluyorum.",
        "Havin'im, her gün seni daha çok sevmek mümkünmüş.",
        "Havin'im, birlikte geçirdiğimiz her an ömrüme ömür katıyor.",
        "Havin'im, sensiz bir hayat düşünemiyorum.",
        "Havin'im, seni tanıdığım için kendimi çok şanslı hissediyorum.",
        "Havin'im, kalbim her zaman seninle.",
        "Havin'im, aşkın hayatımı tamamen değiştirdi.",
        "Havin'im, gülüşün tüm kötü günlerimi aydınlatan bir ışık.",
        "Havin'im, seni sevmek hayatımın en değerli duygusu.",
        "Havin'im, seninle birlikte büyüyen hayallerimiz var.",
        "Havin'im, sana olan sevgim hiçbir zaman son bulmayacak.",
        "Havin'im, seninle olan her anım yaşadığıma değer kılıyor.",
        "Havin'im, adını söylemek bile bana huzur veriyor.",
        "Havin'im, senin yanında olmak benim için en büyük mutluluk.",
        "Havin'im, seni tanıdığım gün hayatımın dönüm noktasıydı.",
        "Havin'im, gözlerindeki aşk dünyadaki en değerli varlığım.",
        "Havin'im, sana olan sevgim her geçen dakika büyüyor.",
        "Havin'im, senin yanında hissettiğim huzur başka hiçbir yerde yok.",
        "Havin'im, seni sevmek yaşamdaki en güzel duygu.",
        "Havin'im, seninle paylaştığım her gülüş hayatımın anlamı.",
        "Havin'im, sensiz geçen her an eksik bir an.",
        "Havin'im, seni özlemek nefes almak kadar doğal.",
        "Havin'im, aşkımız zamanla daha da güçleniyor.",
        "Havin'im, birlikte yürüdüğümüz yol hayatımın en anlamlı serüveni.",
        "Havin'im, gözlerindeki ışıltıyı görmek günümü aydınlatıyor.",
        "Havin'im, senin adını her duyduğumda kalbim hızla çarpıyor.",
        "Havin'im, sana olan sevgim hiçbir şekilde azalmayacak.",
        "Havin'im, birlikte geçirdiğimiz her anın değerini biliyorum.",
        "Havin'im, seni düşünmek bile beni mutlu etmeye yetiyor.",
        "Havin'im, seninle birlikte attığımız her adım benim için çok değerli.",
        "Havin'im, sensiz bir gelecek düşünemiyorum.",
        "Havin'im, sana olan aşkım her geçen gün daha derinleşiyor.",
        "Havin'im, sesini duymak günümün en güzel anlarından biri.",
        "Havin'im, birlikte yaşlandığımızı hayal etmek bile beni mutlu ediyor.",
        "Havin'im, sana olan sevgim sonsuza kadar sürecek.",
        "Havin'im, seninle paylaştığım her an hayatımın zenginliği.",
        "Havin'im, ismini her duyduğumda gülümsüyorum.",
        "Havin'im, senin aşkın beni daha iyi bir insan yapıyor.",
        "Havin'im, seni tanıdığım için çok şanslıyım.",
        "Havin'im, seninle birlikte yaşadığımız her an çok özel.",
        "Havin'im, gözlerine her baktığımda kalbim tekrar aşık oluyor.",
        "Havin'im, seni sevmek hayatımın en anlamlı eylemi.",
        "Havin'im, seninle birlikte olmak en büyük hayalim.",
        "Havin'im, sensiz bir gün bile düşünmek istemiyorum.",
        "Havin'im, sana olan aşkım her gün katlanarak artıyor.",
        "Havin'im, seninle bir ömür geçirmek için doğmuşum sanki.",
        "Havin'im, senin yanında hissettiğim huzur tarif edilemez.",
        "Havin'im, seni düşünmek bile gülümsememe yetiypr.",
        "Havin'im, beraberce kurduğumuz hayaller geleceğimizi aydınlatıyor.",
        "Havin'im, seninle birlikte atmak istediğim daha çok adım var.",
        "Havin'im, hayatımın her anında seni hissediyorum.",
        "Havin'im, sana olan sevgim her geçen gün daha da derinleşiyor.",
        "Havin'im, sesini duymak günümü aydınlatan bir ışık.",
        "Havin'im, birlikte ağladığımız ve güldüğümüz anılar hayatımın hazinesi.",
        "Havin'im, seni sevmek yaşama sebebim.",
        
        // Kalan Romantik Aşk Mesajları (Toplam 1000 mesaj için)
        "Havin'im, seninle paylaştığım her gülüş hayatımın anlamı.",
        "Havin'im, sensiz geçen her an eksik bir an.",
        "Havin'im, seni özlemek nefes almak kadar doğal.",
        "Havin'im, aşkımız zamanla daha da güçleniyor.",
        "Havin'im, birlikte yürüdüğümüz yol hayatımın en anlamlı serüveni.",
        "Havin'im, gözlerindeki ışıltıyı görmek günümü aydınlatıyor.",
        "Havin'im, senin adını her duyduğumda kalbim hızla çarpıyor.",
        "Havin'im, sana olan sevgim hiçbir şekilde azalmayacak.",
        "Havin'im, birlikte geçirdiğimiz her anın değerini biliyorum.",
        "Havin'im, seni düşünmek bile beni mutlu etmeye yetiyor.",
        "Havin'im, seninle birlikte attığımız her adım benim için çok değerli.",
        "Havin'im, sensiz bir gelecek düşünemiyorum.",
        "Havin'im, sana olan aşkım her geçen gün daha derinleşiyor.",
        "Havin'im, sesini duymak günümün en güzel anlarından biri.",
        "Havin'im, birlikte yaşlandığımızı hayal etmek bile beni mutlu ediyor.",
        "Havin'im, sana olan sevgim sonsuza kadar sürecek.",
        "Havin'im, seninle paylaştığım her an hayatımın zenginliği.",
        "Havin'im, kalbimin ritmi senin isminle atiyor.",
        "Havin'im, seninle her anım anlam kazanıyor.",
        "Havin'im, seni her gün daha çok seviyorum.",
        "Havin'im, bir gülüşün dünyamı aydınlatıyor.",
        "Havin'im, seninle geçen her gün yeni bir başlangıç.",
        "Havin'im, ellerinin dokunuşu tenimde kelebek etkisi yaratıyor.",
        "Havin'im, sen benim en değerli hazinemsin.",
        "Havin'im, seninle nefes almak bile bir ayrıcalık.",
        "Havin'im, seni sevmek hayatımın en güzel serüveni.",
        "Havin'im, gökyüzündeki yıldızlar kadar parlak bir geleceğimiz olsun.",
        "Havin'im, sana olan sevgim sonsuzluğun tanımı.",
        "Havin'im, sensiz bir an bile düşünmek istemiyorum.",
        "Havin'im, seninle paylaştığım her an kalbimde saklı.",
        "Havin'im, seni düşünmek kalbimi heyecanla dolduruyor.",
        "Havin'im, seninle kurduğumuz dünyada mutluluk asla eksik olmuyor.",
        "Havin'im, varlığın hayatıma anlam katıyor.",
        "Havin'im, seninle yürüdüğüm her adımda kendimi şanslı hissediyorum.",
        "Havin'im, kokun hafızama öyle işlemiş ki her an yanımdasın.",
        "Havin'im, sana olan sevgim her geçen saniye büyüyor.",
        "Havin'im, gözlerindeki ışık yolumu aydınlatıyor.",
        "Havin'im, seni sevmekten asla vazgeçmeyeceğim.",
        "Havin'im, seninle geçen her an değerinden hiçbir şey kaybetmiyor.",
        "Havin'im, seni düşünmek bile kalbime huzur veriyor.",
        "Havin'im, seninle yarınlara adım atmak en büyük hayalim.",
        "Havin'im, varlığın hayatımın en büyük armağanı.",
        "Havin'im, sana olan sevgimi hiçbir kelime tam olarak anlatamaz.",
        "Havin'im, seninle paylaştığım sessizlikler bile anlam dolu.",
        "Havin'im, yanında olmak her zaman huzur veriyor.",
        "Havin'im, seninle her günün sabahı ayrı güzel.",
        "Havin'im, sana duyduğum aşk her geçen gün daha da büyüyor.",
        "Havin'im, seninle birlikte olmak hayatımın en büyük şansı.",
        "Havin'im, seni özlediğim her an kalbim biraz daha seninle doluyor.",
        "Havin'im, gözlerindeki sevgi beni hayata bağlıyor.",
        "Havin'im, seni sevmek yaşamdaki en büyük mutluluğum.",
        "Havin'im, seninle geçirdiğim her an ruhumu zenginleştiriyor.",
        "Havin'im, seni düşünmeden geçen tek bir günüm bile yok.",
        "Havin'im, seninle kurduğumuz hayaller gerçek olacak.",
        "Havin'im, varlığın her güne anlam katıyor.",
        "Havin'im, sana olan sevgim her gün daha da artıyor.",
        "Havin'im, seni görür görmez kalbim hızla çarpmaya başlıyor.",
        "Havin'im, senin yanında olmak huzur dolu bir rüya gibi.",
        "Havin'im, seni sevmek yaşamın ta kendisi.",
        "Havin'im, seninle geçirdiğim her an bir hazine gibi değerli.",
        "Havin'im, seni düşünmek günümün en güzel anı.",
        "Havin'im, senin sevgin beni her gün daha güçlü kılıyor.",
        "Havin'im, hayatımın anlamını seninle buldum.",
        "Havin'im, sana olan aşkım her geçen gün daha da büyüyor.",
        "Havin'im, gülüşün hayata olan inancımı tazeliyor.",
        "Havin'im, seni seviyorum demek bile yetersiz kalıyor.",
        "Havin'im, seninle her anım ayrı bir hikaye.",
        "Havin'im, kalbimin atış sebebi sensin.",
        "Havin'im, seni özlemek hayatımın rutini oldu.",
        "Havin'im, seninle beraber gülmek dünyadaki en güzel şey.",
        "Havin'im, varlığın hayatımın en büyük hediyesi.",
        "Havin'im, sana olan sevgimi anlatmaya kelimeler yetmiyor.",
        "Havin'im, seninle geçen her an bir mucize gibi.",
        "Havin'im, seni düşünmek bile beni gülümsetiyor.",
        "Havin'im, seni ilk gördüğüm andaki heyecanı hala hissediyorum.",
        "Havin'im, hayatımdaki en değerli varlık sensin.",
        "Havin'im, sana olan sevgim her geçen gün daha da derinleşiyor.",
        "Havin'im, seninle kurduğumuz dünyada mutluluk hiç eksik olmuyor.",
        "Havin'im, sesini duymak günümü aydınlatıyor.",
        "Havin'im, seni sevmek hayatımın en anlamlı eylemi.",
        "Havin'im, seninle hayat çok daha güzel.",
        "Havin'im, beni sevdiğin için çok şanslıyım.",
        "Havin'im, gözlerindeki sevgi dünyadaki en değerli hazine.",
        "Havin'im, seni düşünmek bile kalbimi heyecanlandırıyor.",
        "Havin'im, seninle dünyanın en güzel yerinde olduğumu hissediyorum.",
        "Havin'im, varlığın hayatımın anlamı.",
        "Havin'im, sana olan aşkım her gün kendini yeniliyor.",
        "Havin'im, seninle konuşmak bile beni mutlu etmeye yetiyor.",
        "Havin'im, yanında olmadığım her an eksiklik hissediyorum.",
        "Havin'im, seni sevmek hayatımın amacı.",
        "Havin'im, seninle geçirdiğim her an paha biçilemez.",
        "Havin'im, sesini duymak günümün en güzel anı.",
        "Havin'im, seni düşündüğümde içimi kaplayan sıcaklık tarif edilemez.",
        "Havin'im, hayatım seninle anlam kazanıyor.",
        "Havin'im, sana olan bağlılığım her geçen gün daha da güçleniyor.",
        "Havin'im, gülüşün güneş gibi içimi ısıtıyor.",
        "Havin'im, seni sevdiğim kadar sevilmeyi hak ediyorsun.",
        "Havin'im, seninle birlikte yaşlanmak istiyorum.",
        "Havin'im, aklımın bir köşesinde her zaman sen varsın.",
        "Havin'im, seni sevmek en büyük tutkum.",
        "Havin'im, seninle hayatı keşfetmek en büyük hayalim.",
        "Havin'im, varlığın benim için en büyük hazine.",
        "Havin'im, sana olan sevgim sonsuzluğa uzanıyor.",
        "Havin'im, seninle yaşadığım her an kalbimde iz bırakıyor.",
        "Havin'im, gözlerinde kaybolmak en büyük arzum.",
        "Havin'im, seni düşünmek bile beni mutlu ediyor.",
        "Havin'im, seninle paylaştığım her söz kalbimin derinliklerinden geliyor.",
        "Havin'im, hayatımın her anında seni hissediyorum.",
        "Havin'im, sana olan sevgim her geçen gün katlanarak artıyor.",
        "Havin'im, kokunu her duyduğumda kalbim hızlanıyor.",
        "Havin'im, seni sevdiğimi söylemek en büyük mutluluğum.",
        "Havin'im, seninle birlikte her şey daha anlamlı.",
        "Havin'im, seni düşündüğümde içimi kaplayan sıcaklık paha biçilemez.",
        "Havin'im, senin yanında olmak huzurun ta kendisi.",
        "Havin'im, sana olan aşkım her geçen gün daha da güçleniyor.",
        "Havin'im, seninle paylaştığım her gülüş kalbime işleniyor.",
        "Havin'im, gözlerindeki ışıltı hayatımın anlamı.",
        "Havin'im, seni sevmek hayatımın en doğru kararı.",
        "Havin'im, seninle geçirdiğim her an bir mucize.",
        "Havin'im, varlığın benim için en büyük motivasyon.",
        "Havin'im, sana olan sevgim her geçen gün daha da derinleşiyor.",
        "Havin'im, ismini söylemek bile bana huzur veriyor.",
        "Havin'im, yanımda olmadığın her an seni özlüyorum.",
        "Havin'im, seni sevmek yaşamdaki en büyük şansım.",
        "Havin'im, seninle bir ömür geçirmek en büyük hayalim.",
        "Havin'im, seni düşünmek günümün en güzel anı.",
        "Havin'im, seninle kurduğumuz hayaller geleceğimizi aydınlatıyor.",
        "Havin'im, hayatımın her anında seni hissedebiliyorum.",
        "Havin'im, sana olan sevgim hiçbir zaman solmayacak.",
        "Havin'im, gülüşün kalbimi ısıtıyor.",
        "Havin'im, seni sevdiğim her an biraz daha mutlu oluyorum.",
        "Havin'im, seninle geçirdiğim her an çok özel.",
        "Havin'im, varlığın hayatımın en büyük şansı.",
        "Havin'im, sana dokunabildiğim için çok şanslıyım.",
        "Havin'im, seninle birlikte nefes aldığım her an değerli.",
        "Havin'im, gözlerindeki sevgi dünyadaki en güzel manzara.",
        "Havin'im, seni seviyorum demek hiçbir zaman yeterli gelmiyor.",
        "Havin'im, seninle yaşadığım her an bir hazine.",
        "Havin'im, hayatımın anlamı sensin.",
        "Havin'im, sana olan aşkım sonsuza dek sürecek.",
        "Havin'im, sesini duymak günümü aydınlatan bir ışık.",
        "Havin'im, yanındayken kendimi evimde hissediyorum.",
        "Havin'im, seni sevmek yaşamın en büyük armağanı.",
        "Havin'im, seninle geçirdiğim her an kalbimin hazinesi.",
        "Havin'im, adın dudaklarımdan dökülen en tatlı kelime.",
        "Havin'im, seninle birlikte her şey daha güzel.",
        "Havin'im, varlığın hayatımın en büyük zenginliği.",
        "Havin'im, sana olan sevgimi anlatmak için sonsuz zaman lazım.",
        "Havin'im, seninle her yeni gün bir başka güzel.",
        "Havin'im, kalbim her zaman senin için atacak.",
        "Havin'im, seni sevmek hayatımın en anlamlı kararı.",
        "Havin'im, seninle paylaştığım her an paha biçilemez.",
        "Havin'im, gözlerindeki sevgi benim en büyük zenginliğim.",
        "Havin'im, seni düşünmek kalbimi heyecanla dolduruyor.",
        "Havin'im, senin yanında olmak hayatın en güzel armağanı.",
        "Havin'im, hayatım seninle tam anlamıyla güzel.",
        "Havin'im, sana duyduğum aşk her geçen gün büyüyor.",
        "Havin'im, sesinin tınısı kulaklarımda çınlayan en güzel müzik.",
        "Havin'im, seni sevmek dünyadaki en kolay şey.",
        "Havin'im, seninle olduğum her an çok kıymetli.",
        "Havin'im, varlığınla hayatıma anlam katıyorsun.",
        "Havin'im, sana olan sevgim hiç azalmadan devam ediyor.",
        "Havin'im, senin gülüşün tüm kötü günlerimi unutturuyor.",
        "Havin'im, yanında olmadığım her an seni özlüyorum.",
        "Havin'im, sen olmasaydın hayatım eksik kalırdı.",
        "Havin'im, seninle her yeni güne başlamak bir ayrıcalık.",
        "Havin'im, seni sevmek en büyük şansım.",
        "Havin'im, seninle geçirdiğim her an hayatımın en değerli zamanı.",
        "Havin'im, gözlerindeki ışık geleceğimi aydınlatıyor.",
        "Havin'im, sana olan sevgim her gün bin kat artıyor.",
        "Havin'im, seninle yaşadığım her anı ömrüm boyunca saklayacağım.",
        "Havin'im, seni sevmek nefes almak kadar doğal ve vazgeçilmez.",
        "Havin'im, hayatın anlamını seninle öğrendim.",
        "Havin'im, sana olan aşkım hiçbir zaman son bulmayacak.",
        "Havin'im, seninle kurduğum her hayal, gerçeğe dönüşüyor.",
        "Havin'im, varlığın benim en büyük zenginliğim.",
        "Havin'im, seninle birlikte atmak istediğim daha çok adım var.",
        "Havin'im, gözlerine her baktığımda yeniden aşık oluyorum.",
        "Havin'im, seni seviyorum kelimesi yetersiz kalıyor.",
        "Havin'im, hayat seninle çok daha güzel.",
        "Havin'im, sana olan aşkımı anlatmak için bir ömür yetmez.",
        "Havin'im, seninle her an yeniden başlıyor hayat."
    ];

    // XOX oyun durumu
    const xoxInitialState = {
        board: Array(9).fill(""),
        currentPlayer: "X",
        scores: { X: 0, O: 0 }
    };

    // Hafıza oyun durumu
    const memoryInitialState = {
        matchedPairs: 0,
        moves: 0,
        totalPairs: 0
    };

    // Refleks testi durumu
    const reactionInitialState = {
        bestTime: null,
        lastTime: null
    };
    
    // 2048 oyun durumu
    const game2048InitialState = {
        bestScore: 0
    };
    
    // Tetris oyun durumu
    const tetrisInitialState = {
        highScore: 0,
        level: 1
    };
    
    // Snake oyun durumu
    const snakeInitialState = {
        highScore: 0
    };
    
    // Kelime Tahmin oyun durumu
    const hangmanInitialState = {
        correctWords: 0,
        totalGames: 0,
        bestStreak: 0,
        currentStreak: 0
    };
    
    // Baloncuk Patlatma oyun durumu
    const bubbleInitialState = {
        highScore: 0,
        lastLevel: 1
    };
    
    // Renk Eşleştirme oyun durumu
    const colorMatchInitialState = {
        highScore: 0,
        highestLevel: 1
    };
    
    // Tıklama Yarışı oyun durumu
    const clickRaceInitialState = {
        highScore: 0
    };
    
    // Farkları Bul oyun durumu
    const findDiffInitialState = {
        highScore: 0,
        highestLevel: 1
    };
    
    // Ampul Kırma oyun durumu
    const bulbBreakerInitialState = {
        highScore: 0,
        level: 1
    };
    


    // Yerel depolamadan durumları al veya varsayılanları kullan
    let xoxState = getFromLocalStorage('havin-xox-state', xoxInitialState);
    let memoryState = getFromLocalStorage('havin-memory-state', memoryInitialState);
    let reactionState = getFromLocalStorage('havin-reaction-state', reactionInitialState);
    let game2048State = getFromLocalStorage('havin-2048-state', game2048InitialState);
    let tetrisState = getFromLocalStorage('havin-tetris-state', tetrisInitialState);
    let snakeState = getFromLocalStorage('havin-snake-state', snakeInitialState);
    let hangmanState = getFromLocalStorage('havin-hangman-state', hangmanInitialState);
    let bubbleState = getFromLocalStorage('havin-bubble-state', bubbleInitialState);
    let colorMatchState = getFromLocalStorage('havin-color-match-state', colorMatchInitialState);
    let clickRaceState = getFromLocalStorage('havin-click-race-state', clickRaceInitialState);
    let findDiffState = getFromLocalStorage('havin-find-diff-state', findDiffInitialState);
    let bulbBreakerState = getFromLocalStorage('havin-bulb-breaker-state', bulbBreakerInitialState);

    let loveMessages = DEFAULT_LOVE_MESSAGES;
    let loveMessageVisible = false;
    let currentLoveMessage = "";

    // XOX durumunu güncelle
    function updateXOXState(newState) {
        xoxState = typeof newState === 'function' ? newState(xoxState) : newState;
        saveToLocalStorage('havin-xox-state', xoxState);
        return xoxState;
    }

    // Hafıza oyunu durumunu güncelle
    function updateMemoryState(newState) {
        memoryState = typeof newState === 'function' ? newState(memoryState) : newState;
        saveToLocalStorage('havin-memory-state', memoryState);
        return memoryState;
    }

    // Refleks testi durumunu güncelle
    function updateReactionState(newState) {
        reactionState = typeof newState === 'function' ? newState(reactionState) : newState;
        saveToLocalStorage('havin-reaction-state', reactionState);
        return reactionState;
    }
    
    // 2048 oyunu durumunu güncelle
    function update2048State(newState) {
        game2048State = typeof newState === 'function' ? newState(game2048State) : newState;
        saveToLocalStorage('havin-2048-state', game2048State);
        return game2048State;
    }
    
    // Tetris oyunu durumunu güncelle
    function updateTetrisState(newState) {
        tetrisState = typeof newState === 'function' ? newState(tetrisState) : newState;
        saveToLocalStorage('havin-tetris-state', tetrisState);
        return tetrisState;
    }
    
    // Snake oyunu durumunu güncelle
    function updateSnakeState(newState) {
        snakeState = typeof newState === 'function' ? newState(snakeState) : newState;
        saveToLocalStorage('havin-snake-state', snakeState);
        return snakeState;
    }
    
    // Kelime Tahmin oyunu durumunu güncelle
    function updateHangmanState(newState) {
        hangmanState = typeof newState === 'function' ? newState(hangmanState) : newState;
        saveToLocalStorage('havin-hangman-state', hangmanState);
        return hangmanState;
    }
    
    // Baloncuk Patlatma oyunu durumunu güncelle
    function updateBubbleState(newState) {
        bubbleState = typeof newState === 'function' ? newState(bubbleState) : newState;
        saveToLocalStorage('havin-bubble-state', bubbleState);
        return bubbleState;
    }
    
    // Renk Eşleştirme oyunu durumunu güncelle
    function updateColorMatchState(newState) {
        colorMatchState = typeof newState === 'function' ? newState(colorMatchState) : newState;
        saveToLocalStorage('havin-color-match-state', colorMatchState);
        return colorMatchState;
    }
    
    // Tıklama Yarışı oyunu durumunu güncelle
    function updateClickRaceState(newState) {
        clickRaceState = typeof newState === 'function' ? newState(clickRaceState) : newState;
        saveToLocalStorage('havin-click-race-state', clickRaceState);
        return clickRaceState;
    }
    
    // Farkları Bul oyunu durumunu güncelle
    function updateFindDiffState(newState) {
        findDiffState = typeof newState === 'function' ? newState(findDiffState) : newState;
        saveToLocalStorage('havin-find-diff-state', findDiffState);
        return findDiffState;
    }
    
    // Ampul Kırma oyunu durumunu güncelle
    function updateBulbBreakerState(newState) {
        bulbBreakerState = typeof newState === 'function' ? newState(bulbBreakerState) : newState;
        saveToLocalStorage('havin-bulb-breaker-state', bulbBreakerState);
        return bulbBreakerState;
    }
    


    // Aşk mesajını göster - Bu işlev artık love-letters-game.js dosyasında yer alıyor
    // ve sadece "Havin'e Mektuplar" sayfasında kullanılıyor
    function showLoveMessage() {
        // Bu özellik artık kullanılmıyor. Aşk mesajları sadece 
        // "Havin'e Mektuplar" sayfasında gösteriliyor.
        console.log("Aşk mesajları artık sadece 'Havin'e Mektuplar' sayfasında gösteriliyor.");
    }

    // Aşk mesajını gizle
    function hideLoveMessage() {
        loveMessageVisible = false;
        const modal = document.getElementById('love-message-modal');
        if (modal) {
            modal.classList.remove('active');
        }
    }

    // GameState nesnesini döndür
    return {
        getXOXState: () => xoxState,
        getMemoryState: () => memoryState,
        getReactionState: () => reactionState,
        get2048State: () => game2048State,
        getTetrisState: () => tetrisState,
        getSnakeState: () => snakeState,
        getHangmanState: () => hangmanState,
        getBubbleState: () => bubbleState,
        getColorMatchState: () => colorMatchState,
        getClickRaceState: () => clickRaceState,
        getFindDiffState: () => findDiffState,
        getBulbBreakerState: () => bulbBreakerState,

        updateXOXState,
        updateMemoryState,
        updateReactionState,
        update2048State,
        updateTetrisState,
        updateSnakeState,
        updateHangmanState,
        updateBubbleState,
        updateColorMatchState,
        updateClickRaceState,
        updateFindDiffState,
        updateBulbBreakerState,

        showLoveMessage,
        hideLoveMessage,
        DEFAULT_LOVE_MESSAGES,
        getLoveMessageVisible: () => loveMessageVisible,
        getCurrentLoveMessage: () => currentLoveMessage
    };
})();

// Modal kapatma işlemi
onPageLoad(function() {
    const closeButtons = document.querySelectorAll('.modal-close');
    closeButtons.forEach(button => {
        button.addEventListener('click', function() {
            const modal = this.closest('.modal');
            if (modal) {
                modal.classList.remove('active');
                GameState.hideLoveMessage();
            }
        });
    });
    
    // Arkaplan efektlerini oluştur
    createBackgroundEffects();
});